// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4O44YeHi0R8SpRzCFKKzyZ-OwsL978PI',
    appId: '1:604845155556:web:2c944c9e9b5614155178f1',
    messagingSenderId: '604845155556',
    projectId: 'sev-2-6428b',
    authDomain: 'sev-2-6428b.firebaseapp.com',
    storageBucket: 'sev-2-6428b.appspot.com',
    measurementId: 'G-54NBLXH8C2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxeqrm31FHEqChTF4n1sJab7-Eq_xhTgc',
    appId: '1:604845155556:android:1ce24ac5abc849d05178f1',
    messagingSenderId: '604845155556',
    projectId: 'sev-2-6428b',
    storageBucket: 'sev-2-6428b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_jTjY_lS_njRLB4Fe5P4nB6pzRpCy4Cs',
    appId: '1:604845155556:ios:5418940e6b5c1af65178f1',
    messagingSenderId: '604845155556',
    projectId: 'sev-2-6428b',
    storageBucket: 'sev-2-6428b.appspot.com',
    iosClientId: '604845155556-2prb62u821314574r5b9i0kobmugfeje.apps.googleusercontent.com',
    iosBundleId: 'com.sev2.ios',
  );
}
